services:
  nginx:
    image: nginx
    ports:
      - '80:80'
    volumes:
      - './dist:/var/www/html'
      - './nginx-default.conf:/etc/nginx/conf.d/default.conf'
  npm:
    image: node
    volumes:
      - './src:/var/www/html'
    working_dir: /var/www/html
    entrypoint:
      - npm