services:
  nginx:
    image: nginx
    ports:
      - '80:80'
    volumes:
      - './dist:/var/www/html'
      - './nginx-default.conf:/etc/nginx/conf.d/default.conf'
  npm:
    image: node:alpine
    volumes:
      - './:/var/www/html'
    working_dir: /var/www/html
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '0.5'  # Limit CPU to 50% of one core
    #       memory: '1g'  # Limit memory to 1GB
    entrypoint:
      - npm